sudo: false
language: java
jdk:
  - openjdk11
  - openjdk8
cache:
  directories:
    - "$HOME/.m2/repository"
before_cache:
  - rm -rf $HOME/.m2/repository/org/joda/parent
# install
install:
  - mvn --version
script:
  - mvn install -e -B
